//! Every upstream recipe's JSON encoding must equal the Scala capture byte for
//! byte; the captures we deliberately do not host are listed alongside.
//!
//! The captures are the byte-exact HTTP responses in `capture-scala/` (and
//! `capture-scala-csv/`); a recipe is matched to its capture through the `edit`
//! field, which ends with `/<ObjectName>.scala`. Both `tags` and
//! `inherited_tags` are Scala `Set`s, so this also proves the CHAMP iteration
//! order reproduced by `core::scala_hash`.
//!
//! The captures are Kit's and Alex's *full* corpus, but a deployment hosts a
//! subset of it plus its own recipes, so the captures for the recipes it does
//! not host are recorded as deliberately omitted in
//! `fixtures/omitted_recipes.txt` rather than compared.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;

use recibase_core as core;
use recibase_core::recipe::CHAOS_TAG;

fn capture_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("RECIBASE_CAPTURE_DIR") {
        return PathBuf::from(dir);
    }
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let candidates = [
        manifest
            .join("..")
            .join("..")
            .join("..")
            .join("capture-scala"),
        // The repository keeps its own copy of the captures under tools/.
        manifest
            .join("..")
            .join("..")
            .join("tools")
            .join("harness")
            .join("capture-scala"),
        PathBuf::from("/Users/chaos/recibase-work/capture-scala"),
    ];
    candidates
        .iter()
        .find(|dir| dir.is_dir())
        .cloned()
        .unwrap_or_else(|| panic!("no capture-scala directory; set RECIBASE_CAPTURE_DIR"))
}

/// The captured response body of every recipe, keyed by object name.
fn captured_bodies() -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let mut paths: Vec<PathBuf> = fs::read_dir(capture_dir())
        .expect("read the capture directory")
        .map(|entry| entry.expect("directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "raw"))
        .collect();
    paths.sort();
    for path in paths {
        let raw = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let split = raw
            .windows(4)
            .position(|window| window == b"\r\n\r\n")
            .unwrap_or_else(|| panic!("no header terminator in {}", path.display()));
        let body = String::from_utf8(raw[split + 4..].to_vec())
            .unwrap_or_else(|e| panic!("body of {} is not UTF-8: {e}", path.display()));
        // Only recipe responses carry an `edit` field.
        let Ok(json) = serde_json::from_str::<serde_json::Value>(&body) else {
            continue;
        };
        let Some(edit) = json.get("edit").and_then(|v| v.as_str()) else {
            continue;
        };
        let Some(object_name) = edit
            .strip_suffix(".scala")
            .and_then(|stem| stem.rsplit('/').next())
        else {
            continue;
        };
        // `/recipes/vegetable-primavera` is captured twice; both copies are
        // byte-identical, so the later one simply wins.
        out.insert(object_name.to_string(), body);
    }
    assert!(
        !out.is_empty(),
        "no recipe capture found in {}",
        capture_dir().display()
    );
    out
}

/// The recipe module file for an `object_name`: `BeefStroganoff` ->
/// `crates/core/src/recipes/beef_stroganoff.rs`.
fn recipe_source(object_name: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("recipes")
        .join(format!("{}.rs", core::recipe::snake_case(object_name)));
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// `edit` points at the recipe's source in the deployment's own repository, not
/// the Scala the capture came from, so it is compared by presence, not value.
fn without_edit(body: &str) -> String {
    const KEY: &str = "\"edit\":\"";
    let Some(start) = body.find(KEY) else {
        return body.to_string();
    };
    let value_start = start + KEY.len();
    let Some(length) = body[value_start..].find('"') else {
        return body.to_string();
    };
    let end = value_start + length;
    format!("{}<edit>{}", &body[..value_start], &body[end..])
}

/// Our own recipes (chaos-tagged) are not part of Kit's and Alex's upstream
/// corpus and have no Scala capture, so the byte-for-byte comparison skips them.
/// The list is generated by `crates/core/build.rs` from the `chaos-tag:` markers.
fn is_ours(object_name: &str) -> bool {
    core::recipes::chaos_recipes().contains(&object_name)
}

/// The upstream recipes this deployment deliberately does not host, from
/// `fixtures/omitted_recipes.txt` (`#` comments and blank lines ignored).
const OMITTED: &str = include_str!("fixtures/omitted_recipes.txt");

fn omitted_recipes() -> BTreeSet<String> {
    OMITTED
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string)
        .collect()
}

#[test]
fn every_hosted_recipe_equals_its_capture_byte_for_byte() {
    let captures = captured_bodies();
    let recipes = core::recipes::recipes();
    assert!(!recipes.is_empty(), "the recipe registry is empty");

    // Every upstream recipe we host still matches its capture byte for byte.
    let mut hosted: BTreeSet<String> = BTreeSet::new();
    for recipe in recipes {
        let name = &recipe.object_name;
        // Our own (chaos-tagged) recipes are not part of the upstream corpus
        // and have no Scala capture; the byte-for-byte comparison ignores them.
        if is_ours(name) {
            continue;
        }
        let expected = captures
            .get(name)
            .unwrap_or_else(|| panic!("no capture whose edit ends with /{name}.scala"));
        let actual = core::json::to_string(&recipe.to_json_with_usage(&[]));
        assert_eq!(
            without_edit(&actual),
            without_edit(expected),
            "{name}: the JSON body differs from the Scala capture"
        );
        hosted.insert(name.clone());
    }

    // Every capture is either a recipe we host or one listed as deliberately
    // omitted: a capture that is neither means a recipe was dropped without
    // recording it, and an omitted name we now host means the list is stale.
    let omitted = omitted_recipes();
    assert!(
        omitted.is_disjoint(&hosted),
        "a recipe is both hosted and listed as omitted"
    );
    let captured: BTreeSet<String> = captures.keys().cloned().collect();
    let accounted: BTreeSet<String> = hosted.union(&omitted).cloned().collect();
    assert_eq!(
        accounted,
        captured,
        "captures must be exactly the hosted upstream recipes plus the omitted list\n\
         only in captures: {:?}\nonly in hosted+omitted: {:?}",
        captured.difference(&accounted).collect::<Vec<_>>(),
        accounted.difference(&captured).collect::<Vec<_>>(),
    );
}

/// The generated `chaos_recipes()` list must agree with the `chaos-tag:`
/// markers in the sources, so a renamed or untagged file cannot slip through.
#[test]
fn chaos_recipes_carry_the_chaos_tag_in_their_source() {
    for object_name in core::recipes::chaos_recipes() {
        assert!(
            recipe_source(object_name).contains(CHAOS_TAG),
            "{object_name} is listed in chaos_recipes() but its source has no `{CHAOS_TAG}`"
        );
    }
}
