//! GENERATED by tools/gen_recipes.py - do not edit by hand.

use crate::recipe::RecipeDef;
use std::sync::LazyLock;

pub fn recipes() -> &'static [RecipeDef] {
    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {
        vec![
            super::chilli_con_carne::recipe(),
        ]
    });
    &RECIPES
}
