//! GENERATED by tools/gen_recipes.py - do not edit by hand.

use crate::recipe::RecipeDef;
use std::sync::LazyLock;

pub fn recipes() -> &'static [RecipeDef] {
    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {
        vec![
            super::baked_rigatoni_aubergine::recipe(),
            super::baked_salmon_olives_spaghetti::recipe(),
            super::baobab_ice_cream::recipe(),
            super::basa_pathia::recipe(),
            super::beef_stroganoff::recipe(),
            super::beef_wraps::recipe(),
            super::beetroot_ice_cream::recipe(),
            super::beetroot_risotto::recipe(),
            super::birthday_cake::recipe(),
            super::birthday_cake2::recipe(),
            super::blue_cheese_gnocchi::recipe(),
            super::broccoli_salmon_quiche::recipe(),
            super::broccoli_stilton_soup::recipe(),
            super::brownies::recipe(),
            super::butternut_chilli::recipe(),
            super::butternut_squash_pad_thai::recipe(),
            super::cheese_scones::recipe(),
            super::cheesy_cod_spinach_gratin::recipe(),
            super::chicken_curry::recipe(),
            super::chilli_con_carne::recipe(),
            super::chinese_fusion::recipe(),
            super::chipotle_burgers::recipe(),
            super::chipotle_mac_n_cheese::recipe(),
            super::christmas_naanwidge::recipe(),
            super::chunky_vegetable_crumble::recipe(),
            super::coconut_lime_dahl::recipe(),
            super::cod_with_lentils::recipe(),
            super::courgette_broccoli_pasta::recipe(),
            super::courgette_spinach_pasties::recipe(),
            super::cranberry_relish::recipe(),
            super::creamy_cauliflower_cheese_walnuts::recipe(),
            super::creamy_mushroom_stroganoff::recipe(),
            super::crunch_chocolate_chip_coffee_cake::recipe(),
            super::dahl::recipe(),
            super::dukaten_cookies::recipe(),
            super::egg_tapas::recipe(),
            super::goan_king_prawn_balchao::recipe(),
            super::greek_wraps::recipe(),
            super::halloumi_wraps::recipe(),
            super::hoisin_duck_wraps::recipe(),
            super::indian_patties::recipe(),
            super::kashtouri::recipe(),
            super::lamb_aubergine_daube::recipe(),
            super::lemon_feta_pasta::recipe(),
            super::lentil_shepards_pie::recipe(),
            super::lentil_spinach_stew::recipe(),
            super::macaroni::recipe(),
        ]
    });
    &RECIPES
}
