//! GENERATED by tools/gen_recipes.py - do not edit by hand.

use crate::recipe::RecipeDef;
use std::sync::LazyLock;

pub fn recipes() -> &'static [RecipeDef] {
    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {
        vec![
            super::chilli_con_carne::recipe(),
            super::drop_pancakes::recipe(),
            super::marmalade_ice_cream::recipe(),
            super::mascarpone_ice_cream::recipe(),
            super::mead::recipe(),
            super::melty_mushroom_wellingtons::recipe(),
            super::mexican_polenta_pie::recipe(),
            super::mushroom_quiche::recipe(),
            super::mushroom_risotto::recipe(),
            super::new_york_bagel::recipe(),
            super::nut_roast::recipe(),
            super::pancakes::recipe(),
            super::paneer_jalfrezi::recipe(),
            super::parsnip_ginger_soup::recipe(),
            super::parsnip_lentil_lasagne::recipe(),
            super::peanut_butter_biscuits::recipe(),
            super::pistachio_ice_cream::recipe(),
            super::pomegranate_lime_ice_cream::recipe(),
            super::pomegranate_persian_halloumi::recipe(),
            super::quesadillas::recipe(),
            super::red_pepper_soup::recipe(),
            super::rhubarb_crumble::recipe(),
            super::roast_beetroot_dahl::recipe(),
            super::roasted_artichoke_pasta::recipe(),
            super::roasted_vegetable_lasagne::recipe(),
            super::roasted_vegetable_moroccan_tagine::recipe(),
            super::roasted_vegetable_tart::recipe(),
            super::russian_mushroom_julienne::recipe(),
            super::saag_paneer::recipe(),
            super::scrambled_eggs::recipe(),
            super::seafood_lasagne::recipe(),
            super::shawarma_wraps::recipe(),
            super::smoky_chickpea_stew::recipe(),
            super::smoky_fish_squash_curry::recipe(),
            super::spanakopita::recipe(),
            super::spiced_apple_winter_soup::recipe(),
            super::spicy_smoked_paprika_chorizo::recipe(),
            super::squash_gnocchi_gratin::recipe(),
            super::strawberry_basil_ice_cream::recipe(),
            super::sweet_chilli_feta_pasta::recipe(),
            super::tangy_vegetable_pad_thai::recipe(),
            super::toad_in_the_hole::recipe(),
            super::tofu_katsu_curry::recipe(),
            super::truffle_burgers::recipe(),
            super::turmeric_ginger_ice_cream::recipe(),
            super::vegan_brownies::recipe(),
            super::vegetable_primavera::recipe(),
            super::vegetarian_mexican::recipe(),
            super::wasabi_ice_cream::recipe(),
        ]
    });
    &RECIPES
}
