//! The recipe corpus.
//!
//! One module per Scala `case object ... extends Recipe`.
//! GENERATED by tools/gen_recipes.py - do not edit by hand.

pub mod chilli_con_carne;
pub mod drop_pancakes;
pub mod marmalade_ice_cream;
pub mod mascarpone_ice_cream;
pub mod mead;
pub mod melty_mushroom_wellingtons;
pub mod mexican_polenta_pie;
pub mod mushroom_quiche;
pub mod mushroom_risotto;
pub mod new_york_bagel;
pub mod nut_roast;
pub mod pancakes;
pub mod paneer_jalfrezi;
pub mod parsnip_ginger_soup;
pub mod parsnip_lentil_lasagne;
pub mod peanut_butter_biscuits;
pub mod pistachio_ice_cream;
pub mod pomegranate_lime_ice_cream;
pub mod pomegranate_persian_halloumi;
pub mod quesadillas;
pub mod red_pepper_soup;
pub mod rhubarb_crumble;
pub mod roast_beetroot_dahl;
pub mod roasted_artichoke_pasta;
pub mod roasted_vegetable_lasagne;
pub mod roasted_vegetable_moroccan_tagine;
pub mod roasted_vegetable_tart;
pub mod russian_mushroom_julienne;
pub mod saag_paneer;
pub mod scrambled_eggs;
pub mod seafood_lasagne;
pub mod shawarma_wraps;
pub mod smoky_chickpea_stew;
pub mod smoky_fish_squash_curry;
pub mod spanakopita;
pub mod spiced_apple_winter_soup;
pub mod spicy_smoked_paprika_chorizo;
pub mod squash_gnocchi_gratin;
pub mod strawberry_basil_ice_cream;
pub mod sweet_chilli_feta_pasta;
pub mod tangy_vegetable_pad_thai;
pub mod toad_in_the_hole;
pub mod tofu_katsu_curry;
pub mod truffle_burgers;
pub mod turmeric_ginger_ice_cream;
pub mod vegan_brownies;
pub mod vegetable_primavera;
pub mod vegetarian_mexican;
pub mod wasabi_ice_cream;

pub mod all;

pub use all::recipes;
