//! The recipe corpus.
//!
//! One module per Scala `case object ... extends Recipe`.
//! GENERATED by tools/gen_recipes.py - do not edit by hand.

pub mod chilli_con_carne;

pub mod all;

pub use all::recipes;
