//! GENERATED by tools/gen_recipes.py - do not edit by hand.

use crate::recipe::RecipeDef;
use std::sync::LazyLock;

pub fn recipes() -> &'static [RecipeDef] {
    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {
        vec![
            super::baby_aubergines_stuffed_with_peanut_coconut::recipe(),
            super::baked_rigatoni_aubergine::recipe(),
            super::basil_thyme_roasted_onions_with_squash_goats_cheese_walnuts::recipe(),
            super::beetroot_risotto::recipe(),
            super::blue_cheese_gnocchi::recipe(),
            super::broccoli_salmon_quiche::recipe(),
            super::broccoli_stilton_soup::recipe(),
            super::cheddar_leek_orzotto::recipe(),
            super::coal_smoked_aubergine_curry::recipe(),
            super::coconut_lime_dahl::recipe(),
            super::coconut_potato_curry::recipe(),
            super::creamy_leek_croustade::recipe(),
            super::creamy_mushroom_stroganoff::recipe(),
            super::crispy_gnocchi_with_roasted_peppers_chilli_rosemary_and_ricotta::recipe(),
            super::dahl::recipe(),
            super::easy_pancakes::recipe(),
            super::fish_finger_katsu::recipe(),
            super::kimchi_noodles::recipe(),
            super::lemon_pea_risotto::recipe(),
            super::med_style_gnocchi::recipe(),
            super::melty_mushroom_wellingtons::recipe(),
            super::mexican_polenta_pie::recipe(),
            super::miso_asparagus_rice_bowls::recipe(),
            super::miso_tofu_aubergine::recipe(),
            super::mushroom_risotto::recipe(),
            super::olive_pesto_casarecce::recipe(),
            super::oven_baked_shakshuka_roasted_peppers_tomatoes_chilli_with_eggs::recipe(),
            super::pasta_primavera::recipe(),
            super::polenta_with_balsamic_sausages_mushrooms::recipe(),
            super::prosciutto_cabbage_bean_stew::recipe(),
            super::pumpkin_black_eyed_bean_coconut_curry::recipe(),
            super::quick_roasted_fennel_and_bulgur_wheat_with_mozzarella_figs_pomegranate_and_dill::recipe(),
            super::ras_el_hanout_slow_roasted_mushrooms_with_pink_peppercorns_halloumi_flat_leaf_parsley::recipe(),
            super::red_pepper_and_almond_linguine::recipe(),
            super::roast_beetroot_dahl::recipe(),
            super::simple_vegetable_stir_fry::recipe(),
            super::spiced_apple_winter_soup::recipe(),
            super::spicy_smoked_paprika_chorizo::recipe(),
            super::spinach_tomato_chickpea_curry::recipe(),
            super::squash_and_sage_puff_tart::recipe(),
            super::squash_gnocchi_gratin::recipe(),
            super::squash_sweet_potato_lentil_stew::recipe(),
            super::summertime_mac_n_cheese::recipe(),
            super::toad_in_the_hole::recipe(),
            super::tomato_curry::recipe(),
            super::venison_meatballs_with_spiced_swede_mash::recipe(),
            super::warming_sweet_potato_mushroom_polenta_with_tomatoes::recipe(),
        ]
    });
    &RECIPES
}

/// The `object_name`s of recipes that are ours (the files carrying
/// `chaos-tag:`). `recipe_corpus` skips them, and the API marks their
/// list entries so the frontend can tell them from the upstream corpus.
pub fn chaos_recipes() -> &'static [&'static str] {
    &[
        "BabyAuberginesStuffedWithPeanutCoconut",
        "BasilThymeRoastedOnionsWithSquashGoatsCheeseWalnuts",
        "CheddarLeekOrzotto",
        "CoalSmokedAubergineCurry",
        "CoconutPotatoCurry",
        "CreamyLeekCroustade",
        "CrispyGnocchiWithRoastedPeppersChilliRosemaryAndRicotta",
        "EasyPancakes",
        "FishFingerKatsu",
        "KimchiNoodles",
        "LemonPeaRisotto",
        "MedStyleGnocchi",
        "MisoAsparagusRiceBowls",
        "MisoTofuAubergine",
        "OlivePestoCasarecce",
        "OvenBakedShakshukaRoastedPeppersTomatoesChilliWithEggs",
        "PastaPrimavera",
        "PolentaWithBalsamicSausagesMushrooms",
        "ProsciuttoCabbageBeanStew",
        "PumpkinBlackEyedBeanCoconutCurry",
        "QuickRoastedFennelAndBulgurWheatWithMozzarellaFigsPomegranateAndDill",
        "RasElHanoutSlowRoastedMushroomsWithPinkPeppercornsHalloumiFlatLeafParsley",
        "RedPepperAndAlmondLinguine",
        "SimpleVegetableStirFry",
        "SpinachTomatoChickpeaCurry",
        "SquashAndSagePuffTart",
        "SquashSweetPotatoLentilStew",
        "SummertimeMacNCheese",
        "TomatoCurry",
        "VenisonMeatballsWithSpicedSwedeMash",
        "WarmingSweetPotatoMushroomPolentaWithTomatoes",
    ]
}
