//! The recipe corpus.
//!
//! One module per Scala `case object ... extends Recipe`.
//! GENERATED by tools/gen_recipes.py - do not edit by hand.

pub mod baby_aubergines_stuffed_with_peanut_coconut;
pub mod baked_rigatoni_aubergine;
pub mod basil_thyme_roasted_onions_with_squash_goats_cheese_walnuts;
pub mod beetroot_risotto;
pub mod blue_cheese_gnocchi;
pub mod broccoli_salmon_quiche;
pub mod broccoli_stilton_soup;
pub mod cheddar_leek_orzotto;
pub mod coal_smoked_aubergine_curry;
pub mod coconut_lime_dahl;
pub mod coconut_potato_curry;
pub mod creamy_leek_croustade;
pub mod creamy_mushroom_stroganoff;
pub mod crispy_gnocchi_with_roasted_peppers_chilli_rosemary_and_ricotta;
pub mod dahl;
pub mod easy_pancakes;
pub mod fish_finger_katsu;
pub mod kimchi_noodles;
pub mod lemon_pea_risotto;
pub mod med_style_gnocchi;
pub mod melty_mushroom_wellingtons;
pub mod mexican_polenta_pie;
pub mod miso_asparagus_rice_bowls;
pub mod miso_tofu_aubergine;
pub mod mushroom_risotto;
pub mod olive_pesto_casarecce;
pub mod oven_baked_shakshuka_roasted_peppers_tomatoes_chilli_with_eggs;
pub mod pasta_primavera;
pub mod polenta_with_balsamic_sausages_mushrooms;
pub mod prosciutto_cabbage_bean_stew;
pub mod pumpkin_black_eyed_bean_coconut_curry;
pub mod quick_roasted_fennel_and_bulgur_wheat_with_mozzarella_figs_pomegranate_and_dill;
pub mod ras_el_hanout_slow_roasted_mushrooms_with_pink_peppercorns_halloumi_flat_leaf_parsley;
pub mod red_pepper_and_almond_linguine;
pub mod roast_beetroot_dahl;
pub mod simple_vegetable_stir_fry;
pub mod spiced_apple_winter_soup;
pub mod spicy_smoked_paprika_chorizo;
pub mod spinach_tomato_chickpea_curry;
pub mod squash_and_sage_puff_tart;
pub mod squash_gnocchi_gratin;
pub mod squash_sweet_potato_lentil_stew;
pub mod summertime_mac_n_cheese;
pub mod toad_in_the_hole;
pub mod tomato_curry;
pub mod venison_meatballs_with_spiced_swede_mash;
pub mod warming_sweet_potato_mushroom_polenta_with_tomatoes;

pub mod all;

pub use all::{chaos_recipes, recipes};
