#!/usr/bin/env python3
"""Regenerate crates/core/src/recipes/mod.rs and crates/core/src/recipes/all.rs.

Scans crates/core/src/recipes/*.rs (one file per recipe, named after the Scala
case object) and writes the module list plus the registry. Recipe order does
not affect byte compatibility: every consumer treats the corpus as a Set or
sorts it, and the Scala side's reflection order is itself unstable.

A recipe file that carries the chaos tag (`chaos-tag:`, see
`recibase_core::recipe::CHAOS_TAG`) is ours rather than part of Kit's and Alex's
upstream corpus. Its `object_name` is collected into `chaos_recipes()`, which the
byte-for-byte corpus test skips and the API uses to mark list entries.
"""
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
recipes_dir = os.path.join(here, os.pardir, "crates", "core", "src", "recipes")
recipes_dir = os.path.normpath(recipes_dir)

CHAOS_MARKER = "chaos-tag:"
OBJECT_NAME = re.compile(r'object_name:\s*"([^"]+)"')

def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()

def chaos_names(files):
    names = []
    for name in files:
        with open(os.path.join(recipes_dir, name)) as fh:
            source = fh.read()
        if CHAOS_MARKER in source:
            match = OBJECT_NAME.search(source)
            if match is None:
                sys.exit(f"{name}: carries the chaos tag but has no object_name")
            names.append(match.group(1))
    return sorted(names)

def main():
    files = sorted(f for f in os.listdir(recipes_dir)
                   if f.endswith(".rs") and f not in ("mod.rs", "all.rs"))
    mods = [(f[:-3], snake(f[:-3])) for f in files]
    chaos = chaos_names(files)
    with open(os.path.join(recipes_dir, "mod.rs"), "w") as fh:
        fh.write("//! The recipe corpus.\n//!\n"
                 "//! One module per Scala `case object ... extends Recipe`.\n"
                 "//! GENERATED by tools/gen_recipes.py - do not edit by hand.\n\n")
        for obj, mod in mods:
            fh.write(f"pub mod {mod};\n")
        fh.write("\npub mod all;\n\npub use all::{chaos_recipes, recipes};\n")
    with open(os.path.join(recipes_dir, "all.rs"), "w") as fh:
        fh.write("//! GENERATED by tools/gen_recipes.py - do not edit by hand.\n\n"
                 "use crate::recipe::RecipeDef;\nuse std::sync::LazyLock;\n\n"
                 "pub fn recipes() -> &'static [RecipeDef] {\n"
                 "    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {\n"
                 "        vec![\n")
        for obj, mod in mods:
            fh.write(f"            super::{mod}::recipe(),\n")
        fh.write("        ]\n    });\n    &RECIPES\n}\n")
        fh.write("\n/// The `object_name`s of recipes that are ours (the files carrying\n"
                 "/// `chaos-tag:`). `recipe_corpus` skips them, and the API marks their\n"
                 "/// list entries so the frontend can tell them from the upstream corpus.\n"
                 "pub fn chaos_recipes() -> &'static [&'static str] {\n    &[\n")
        for name in chaos:
            fh.write(f'        "{name}",\n')
        fh.write("    ]\n}\n")
    print(f"wrote {len(mods)} recipe modules, {len(chaos)} chaos-tagged")

if __name__ == "__main__":
    main()
