#!/usr/bin/env python3
"""Regenerate core/src/recipes/mod.rs and core/src/recipes/all.rs.

Scans core/src/recipes/*.rs (one file per recipe, named after the Scala case
object) and writes the module list plus the registry. Recipe order does not
affect byte compatibility: every consumer treats the corpus as a Set or sorts
it, and the Scala side's reflection order is itself unstable.
"""
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
recipes_dir = os.path.join(here, os.pardir, "core", "src", "recipes")
recipes_dir = os.path.normpath(recipes_dir)

def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()

def main():
    files = sorted(f for f in os.listdir(recipes_dir)
                   if f.endswith(".rs") and f not in ("mod.rs", "all.rs"))
    mods = [(f[:-3], snake(f[:-3])) for f in files]
    with open(os.path.join(recipes_dir, "mod.rs"), "w") as fh:
        fh.write("//! The recipe corpus.\n//!\n"
                 "//! One module per Scala `case object ... extends Recipe`.\n"
                 "//! GENERATED by tools/gen_recipes.py - do not edit by hand.\n\n")
        for obj, mod in mods:
            fh.write(f"pub mod {mod};\n")
        fh.write("\npub mod all;\n\npub use all::recipes;\n")
    with open(os.path.join(recipes_dir, "all.rs"), "w") as fh:
        fh.write("//! GENERATED by tools/gen_recipes.py - do not edit by hand.\n\n"
                 "use crate::recipe::RecipeDef;\nuse std::sync::LazyLock;\n\n"
                 "pub fn recipes() -> &'static [RecipeDef] {\n"
                 "    static RECIPES: LazyLock<Vec<RecipeDef>> = LazyLock::new(|| {\n"
                 "        vec![\n")
        for obj, mod in mods:
            fh.write(f"            super::{mod}::recipe(),\n")
        fh.write("        ]\n    });\n    &RECIPES\n}\n")
    print(f"wrote {len(mods)} recipe modules")

if __name__ == "__main__":
    main()
